version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: resume-landing-app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://root:securepass@db:3306/resume
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npm run dev"

  db:
    image: mariadb:10.9
    container_name: resume-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securepass
      MYSQL_DATABASE: resume
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
