import '../../lib/fontawesome'
import '../../styles/globals.css'
import { robotoMono, robotoSlab } from '@/lib/fonts'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
